version: '3'
services:
  db:
    image: postgres:12
    ports:
      - ${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DABATASE_NAME}